(function(document) {
	document.open();

	var styles = [
		// inputManager
		"modules/inputManager/styles/currentInputDisplay.css"
	];

	styles.forEach(function(path) {
		var link = document.createElement("link");
		link.rel = "stylesheet";
		link.type = "text/css";
		link.href = path;
		document.head.appendChild(link);
	});

	var scripts = [
		"lib/angular.min.js",
		"lib/lodash.min.js",

		// eventManager
		"modules/eventManager/scripts/eventManager.module.js",
		"modules/eventManager/scripts/eventManager.constants.js",
		"modules/eventManager/scripts/eventManager.factory.js",

		// inputManager
		"modules/inputManager/scripts/inputManager.module.js",
		"modules/inputManager/scripts/inputManager.constants.js",
		"modules/inputManager/scripts/captureKeyPress.directive.js",
		"modules/inputManager/scripts/currentInputDisplay.directive.js",
		"modules/inputManager/scripts/inputManager.factory.js",

		// preferencesManager
		"modules/preferencesManager/scripts/preferencesManager.module.js",
		"modules/preferencesManager/scripts/preferencesManager.factory.js",

		//htmlTemplateCacher NOTE: This module is generated by `grunt ngtemplates:dev`
		"modules/htmlTemplateCacher/scripts/htmlTemplateCacher.module.js",

		"app.js"
	];

	scripts.forEach(function(path) {
		var link = document.createElement("script");
		link.type = "text/javascript";
		link.src = path;
		document.body.appendChild(link);
	});

	document.close();
}(document));
